### PR TITLE
Match Create a generator menu items with subsections

### PR DESCRIPTION
**Pull request by Saitama2016**
I went to the JavaScript file responsible for rendering the Side Navigation Bar and changed the name of the menu items indicated in the issue.

### CODE REVIEW

**Comment by Rantelo** [comment]
Hello @Saitama2016 
Thanks for your contribution.
Sadly, the change is performed in the wrong place. See, the file you changed is one automatically generated after ReactStatic compiles and bundle our documentation.
If you still are interested in submitting the PR, please remove the change you did in _docs/static.something.js_ and instead put it in _wizardo/docs_source/src/components/Navbar.js_.

I hope to see you around and that Wizardo is useful to you too.

**Comment by Saitama2016** [comment]
Hello, @Rantelo Thanks for reviewing my code. I will make the changes right now to complete the Pull Request.

**Comment by Saitama2016** [comment]
Hello, @Rantelo I committed the changes to Navbar component just now.

**Comment by iburgos72** [comment]
@Saitama2016, thank you for solve the problem with the menu items :+1: 

Just one thing, can you return the changes in the `docs/static.ff12f074.js` file?
The file is generated automatically when @Rantelo or me run the command for build the assets, so, is not necessary make changes in that file.

**Comment by iburgos72** [comment]
ok, i don't know why but github show the file like if you changed the code.

**Pull request merged**
